package io.tradecraft.common.envelope;

public enum Stage {
    FIX_RECV, FIX_TO_EVENT,
    EV_RECV, EV_NEW,
    OMS_ROUTE_PARENT, OMS_CANCEL_PARENT,
    SOR_ROUTE_PARENT, SOR_ROUTE_CHILD, SOR_CANCEL_CHILD,
    SOR_SEND_CHILD_ORDER, SOR_SEND_CANCEL_ORDER, SOR_SEND_REPLACE_ORDER,
    VENUE_RECV_ORDER, VENUE_RECV_CANCEL_ORDER, VENUE_RECV_REPLACE_ORDER, VENUE_ACCEPTED,
    VENUE_ACK_SENT, VENUE_FILLED_SENT, VENUE_CANCEL_SENT, VENUE_REPLACE_SENT,
    SOR_RECV_ACK, SOR_RECV_FILLED, SOR_RECV_CANCEL, SOR_RECV_REPLACE,
    OMS_PUB_ACKED, OMS_PUB_FILLED, OMS_PUB_CANCEL,
    OMS_RECV_FILLED, OMS_RECV_FILLED_DUP, OMS_RECV_CANCEL_DUP,
    ER_RECV_ACK, ER_RECV_FILLED, ER_RECV_CANCELLED,
    FIX_OUT,
    UNKNOWN
}
